name: 'Mutating tictactoe'

on:
    push:
        branches:
            - master

jobs:
    run-pitest:
        runs-on: ubuntu-latest
        steps:
            - name: Install maven
              uses: xlui/action-maven-cli@v1.0

            - name: Install dependencies
              run: mvn clean install

            - name: Run pitest
              run: mvn org.pitest:pitest-maven:mutationCoverage

